version: '3'
services:
  docker-from-docker:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000
        USERNAME: mozaik
    volumes:
      - ../mozaik:/usr/local/lib/python3.7/site-packages/mozaik
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker-host.sock 

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity 
