name: Mozaik Setup

on:
  workflow_call: # Allows this workflow to be called from other workflows
    inputs:
      pytest-args:
        description: 'Arguments to pass to pytest'
        required: true
        type: string

jobs:
  setup-mozaik-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Pytest Unit Tests
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install python3-setuptools subversion git libopenmpi-dev g++ libjpeg8 libjpeg8-dev libfreetype6 libfreetype6-dev zlib1g-dev libpng++-dev libncurses6 libncurses-dev libreadline-dev liblapack-dev libblas-dev gfortran libgsl0-dev openmpi-bin python3-tk cmake
        pip3 install pytest pytest-cov pytest-randomly coverage black
        # TODO: Add pynn once we switch from our custom to the official release
        pip3 install numpy scipy mpi4py matplotlib quantities lazyarray interval Pillow param==1.5.1 parameters neo==0.12.0 cython==3.0.10 psutil future requests elephant pytest-xdist pytest-timeout junitparser numba numpyencoder sphinx imageio

    - name: Download and install imagen
      run: |
        git clone https://github.com/antolikjan/imagen.git
        cd imagen
        pip install .
        cd ..

    # TODO: Remove this block once we switch from our custom pynn to the official release
    - name: Download and install PyNN
      run: |
        git clone https://github.com/CSNG-MFF/PyNN.git
        cd PyNN
        git checkout PyNNStepCurrentModule
        pip install .
        cd ..

    - name: Install Nest
      run: |
        wget https://github.com/nest/nest-simulator/archive/v3.4.tar.gz
        tar xvfz v3.4.tar.gz
        cd nest-simulator-3.4
        cmake -Dwith-mpi=ON -Dwith-boost=ON -DCMAKE_INSTALL_PREFIX:PATH=$pythonLocation -Dwith-optimize='-O3' ./
        make -j8
        make -j8 install
        cd ..
        python -c 'import nest'

    - name: Install stepcurrentmodule
      run: |
        git clone https://github.com/CSNG-MFF/nest-step-current-module.git
        cd nest-step-current-module
        cmake -Dwith-mpi=ON -Dwith-boost=ON -Dwith-nest=$pythonLocation/bin/nest-config -Dwith-optimize='-O3' ./
        make -j8
        make -j8 install
        cd ..

    - name: Install mozaik
      run: pip install .

    - name: Run pytests
      run: pytest ${{ inputs.pytest-args }} tests --cov=mozaik
